name: CI/CD

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Generate .env
        run: |
          echo -e "REACT_APP_FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}}\nREACT_APP_FIREBASE_AUTH_DOMAIN=${{secrets.FIREBASE_AUTH_DOMAIN}}\nREACT_APP_FIREBASE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}}\nREACT_APP_FIREBASE_STORAGE_BUCKET=${{secrets.FIREBASE_STORAGE_BUCKET}}\nREACT_APP_FIREBASE_MESSAGING_SEND_ID=${{secrets.FIREBASE_MESSAGING_SEND_ID }}\nREACT_APP_FIREBASE_APP_ID=${{secrets.FIREBASE_APP_ID}}\nREACT_APP_FIREBASE_MEASUREMENT_ID=${{secrets.FIREBASE_MEASUREMENT_ID}}" > .env
      - name: Build
        env:
          CI: false
        run: |
          npm install
          npm run build
      - name: Deploy
        run: |
          npx firebase deploy --only hosting --token "${{secrets.FIREBASE_TOKEN}}"

  automerge:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - id: automerge
        if: ${{contains(github.event.*.labels.*.name, 'automerge')}}
        name: automerge
        uses: 'pascalgn/automerge-action@v0.15.3'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
